language: c
sudo: required
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam
    - gfortran
  homebrew:
    packages:
    - ocaml
    - opam
    update: true

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install gcc --enable-fortran || true;
      brew link --overwrite gcc;
    fi
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - FORK_USER=Chris00
  matrix:
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
os:
  - linux
  - osx

notifications:
  email:
    - Christophe.Troestler@umons.ac.be
